### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email":  "sample01@example.com",
  "password": "password"
}

### Login

POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email":  "sample01@example.com",
  "password": "password"
}

### Get the currently signin user
GET http://localhost:3000/auth/whoami

### Find a particular user with a given ID
GET http://localhost:3000/auth/2


### Find all users with a given email
GET http://localhost:3000/auth/?email=sample@example.com

### Delete a user giben id
DELETE http://localhost:3000/auth/123131

### Update a user
PATCH http://localhost:3000/auth/6666
Content-Type: application/json

{
  "email": "aaaa@aaaa.com",
  "password": "bbbb"
}
